### ISSUE TITLE
`SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 96` on `User authorization failed: no access_token passed` error

### ISSUE THREAD

**Issue by konard** [Konard/vk#11]
```
{
  "error": {
    "error_code": 5,
    "error_msg": "User authorization failed: no access_token passed.",
    "request_params": [
      {
        "key": "v",
        "value": "5.131"
      },
      {
        "key": "method",
        "value": "execute.acceptAllFriendRequests"
      },
      {
        "key": "oauth",
        "value": "1"
      }
    ]
  }
}
FAIL ./DefaultSuite.test.js
  ● Test suite failed to run

    SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 96
    Current browser version is 98.0.4758.80 with binary path /usr/bin/google-chrome

      at Object.throwDecodedError (../../../../../.nvm/versions/node/v14.18.2/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/error.js:550:15)
      at parseHttpResponse (../../../../../.nvm/versions/node/v14.18.2/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:560:13)
      at Executor.execute (../../../../../.nvm/versions/node/v14.18.2/lib/node_modules/selenium-side-runner/node_modules/selenium-webdriver/lib/http.js:486:26)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.595s
Ran all test suites.
Token is updated
```

**Comment by konard** [comment]
Running this command again solves the issue.
```
npm install -g chromedriver --unsafe-perm=true --allow-root
```
